### ISSUE TITLE
CSS居中(垂直, 水平)

### ISSUE THREAD

**Issue by ygxqqx** [ygxqqx/collection#2]
- ## [Centering in CSS: A Complete Guide](https://css-tricks.com/centering-css-complete-guide/)
---
-  ## [span 画横线](https://ygxqqx.github.io/ife2016/task07/)
```css
span {
    display: inline-block;
    width: 34px;
    height: 11px;
    color: #fff;
    border-top: 2px solid #fff;
    margin-top: 15px;
    transition: all 0.5s ease-out 0s;
}
```
---
